Repository zyantific/zydis, pull requests merged in 2021-09, with the labels that each got.

#218 CI: test build of VS projects in `msvc` directory
  .github/workflows/main.yml
Labels: C-enhancement, P-medium, A-build

#216 Update MSVC project files
  msvc/Zydis.sln
  msvc/dependencies/zycore/Zycore.vcxproj
  msvc/dependencies/zycore/Zycore.vcxproj.filters
  msvc/examples/ZydisWinKernel.vcxproj
  msvc/zydis/Zydis.vcxproj
  msvc/zydis/Zydis.vcxproj.filters
Labels: C-enhancement, P-medium, A-build

#228 Fuzzing: validate enum ranges
  tools/ZydisFuzzIn.c
Labels: C-enhancement, P-medium, A-utils

#234 Do not sign ZydisWinKernel sample
  msvc/examples/ZydisWinKernel.vcxproj
Labels: C-bug, P-medium, A-build
