Repository zyantific/zydis, pull requests merged in 2021-11, with the labels that each got.

#259 Fix build on macOS 12
  include/Zydis/ShortString.h
Labels: C-enhancement, P-medium, A-build

#262 Remove deprecated `accessed_flags` flags field from `ZydisDecodedInstruction`
  include/Zydis/DecoderTypes.h
  include/Zydis/Internal/SharedData.h
  include/Zydis/Utils.h
  src/Decoder.c
  src/Encoder.c
  src/Generated/AccessedFlags.inc
  src/SharedData.c
  src/Utils.c
  tests/cases/default_001.out
  tests/cases/default_002.out
  tests/cases/default_004.out
  tests/cases/default_007.out
  tests/cases/default_008.out
  tests/cases/default_011.out
  tests/cases/default_013.out
  tests/cases/default_014.out
  tests/cases/default_015.out
  tests/cases/default_018.out
  tests/cases/default_022.out
  tests/cases/default_036.out
  tests/cases/evex_025.out
  tools/ZydisFuzzDecoder.c
  tools/ZydisFuzzShared.c
  tools/ZydisFuzzShared.h
  tools/ZydisInfo.c
Labels: C-cleanup, A-decoder, P-medium

#267 docs: add man pages
  CMakeLists.txt
  man/ZydisDisasm.1.ronn
  man/ZydisInfo.1.ronn
Labels: C-enhancement, A-doc, P-medium

#272 Add encoder tests to CI
  .github/workflows/main.yml
  tools/ZydisFuzzShared.c
Labels: C-enhancement, P-medium, A-build

#273 Fixed build in minimal mode
  include/Zydis/Internal/SharedData.h
Labels: C-bug, A-decoder, P-medium

#274 Add a minimal mode build to CI
  .github/workflows/main.yml
Labels: C-enhancement, P-medium, A-build

#275 Add regression tests for recent bugs
  tests/cases/vexc4_025.in
  tests/cases/vexc4_025.out
  tests/enc_test_cases.json
Labels: C-enhancement, A-decoder, P-medium
