Repository zyantific/zydis, pull requests merged in 2022-11, with the labels that each got.

#401 Disassembler: fix argument type `usize` -> `u64`
  include/Zydis/Disassembler.h
  src/Disassembler.c
Labels: C-bug, A-decoder

#404 Optimize logo for darkmode and add logos to assets folder
  README.md
  assets/img/logo-dark.svg
  assets/img/logo-light.svg
Labels: C-enhancement, A-doc

#408 Fix `ZydisFeature` enum max value constant
  include/Zydis/Zydis.h
Labels: C-bug
