Repository zyantific/zydis, pull requests merged in 2022-10, with the labels that each got.

#383 Add support for ppc(64) and riscv64
  src/String.c
Labels: A-build

#385 CMake: rename target `doc` -> `ZydisDoc`
  CMakeLists.txt
Labels: A-build

#387 Makefile: fix `test` recipe
  Makefile
Labels: C-bug, P-low, A-build

#386 Decoder: consistent handling of NULL buffer
  src/Decoder.c
Labels: C-bug, A-decoder, P-low
