Repository zyantific/zydis, pull requests merged in 2024-02, with the labels that each got.

#481 Keep same order of files for amalgamation
  assets/amalgamate.py
Labels: C-enhancement, A-build

#482 Make: support generating clangd DB
  .gitignore
  Makefile
Labels: C-feature, A-build

#483 Doc: mention register scaling changes in v5 porting guide
  assets/porting-guide-v4-v5.md
Labels: C-enhancement, A-doc

#485 README: mention v4 maintenance branch
  README.md
Labels: A-doc
